### ISSUE TITLE
Flying over a cube breaks PX4 terrain distance estimator

### ISSUE THREAD

**Issue by timkondratev** [CopterExpress/clover_vm#14]
Same for spawning a cube below a flying drone or removing a cube.

Topic `/mavros/altitude` displays sudden change in terrain distance and then `nan`:
```
header: 
  seq: 616
  stamp: 
    secs: 62
    nsecs:  40000000
  frame_id: "map"
monotonic: 489.8117980957031
amsl: 489.8117980957031
local: 2.0768721103668213
relative: 2.0768721103668213
terrain: nan
bottom_clearance: nan
```
